botserverHost: "127.0.0.1"      # BotServer Listening Interface
botserverPort: 6667             # BotServer TCP Port
botserverTimeout: 60            # BotServer TCP Socket Timeout

language:                       # bot language for lemmatizer
    - it
    - en

chatThreshold: 0.65             # chatbot recognition threshold

# List of allowed clients, with certificates (common name: CN)
allowedClients:
    - botctl
