#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SETUP - Import and download all required settings for this project
#

# System imports
import os
import sys
print("- Checking required project imports", flush=True)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
try:
    # SSL and the liking
    import ssl
    import OpenSSL
    # YAML (mostly pyyaml) module
    import yaml
    # NLTK and KERAS, all others are dependencies
    import nltk
    import numpy
    import keras
    import pickle
    import tensorflow
    # Multi language capable lemmatizer
    import simplemma
except ModuleNotFoundError as E:
    print(f"{E}. Install required modules.")
    sys.exit(1)

# Downloading additional data, when needed
print("- Downloading NLTK data requirements", flush=True)
# nltk.download()   Use this one to get a XWindow GUI interface to pick your favorite database
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('snowball_data')

# Basic directories
os.makedirs('db',       exist_ok=True)      # Database directory
os.makedirs('certs',    exist_ok=True)      # Server certificates directory

print("\n- Setup completed, now you're ready to train your model\n")